language: php

php:
    - 7.0
    - 7.1

before_script:
    - cp app/config/parameters.yml.test app/config/parameters.yml
    - composer install --prefer-dist
    - ./app/console --version
    - ./bin/travis

branches:
    only:
        - master
        - develop

script: ./bin/phpunit -c app/
