security:
    providers:
        main:
            entity:
                class: Madalynn\Bundle\MainBundle\Entity\User
                property: username
    encoders:
        Madalynn\Bundle\MainBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: /admin
            anonymous: true
            form_login:
                login_path: login
                use_forward: false
                check_path: login_check
                failure_path: null
            logout:
                path: logout
            remember_me:
                secret: %secret%
                lifetime: 31536000
                path: /
                domain: ~
    access_control:
        - { path: /admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin, role: ROLE_ADMIN }
