admin_android_version_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:AndroidVersion:list", page: 1 }
    requirements:
        page:  \d+

admin_android_version_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:AndroidVersion:filter" }

admin_android_version_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:AndroidVersion:clear" }

admin_android_version_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:AndroidVersion:show" }

admin_android_version_new:
    path:  /new
    defaults: { _controller: "AdminBundle:AndroidVersion:new" }

admin_android_version_create:
    path:  /create
    defaults: { _controller: "AdminBundle:AndroidVersion:create" }
    methods: [POST]

admin_android_version_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:AndroidVersion:edit" }

admin_android_version_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:AndroidVersion:update" }
    methods: [POST]

admin_android_version_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:AndroidVersion:delete" }
