admin_androirc_version_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:AndroircVersion:list", page: 1 }
    requirements:
        page:  \d+

admin_androirc_version_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:AndroircVersion:filter" }

admin_androirc_version_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:AndroircVersion:clear" }

admin_androirc_version_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:AndroircVersion:show" }

admin_androirc_version_new:
    path:  /new
    defaults: { _controller: "AdminBundle:AndroircVersion:new" }

admin_androirc_version_create:
    path:  /create
    defaults: { _controller: "AdminBundle:AndroircVersion:create" }
    methods: [POST]

admin_androirc_version_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:AndroircVersion:edit" }

admin_androirc_version_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:AndroircVersion:update" }
    methods: [POST]

admin_androirc_version_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:AndroircVersion:delete" }
