admin_article_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:Article:list", page: 1 }
    requirements:
        page:  \d+

admin_article_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:Article:filter" }

admin_article_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:Article:clear" }

admin_article_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:Article:show" }

admin_article_new:
    path:  /new
    defaults: { _controller: "AdminBundle:Article:new" }

admin_article_create:
    path:  /create
    defaults: { _controller: "AdminBundle:Article:create" }
    methods: [POST]

admin_article_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:Article:edit" }

admin_article_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:Article:update" }
    methods: [POST]

admin_article_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:Article:delete" }
