admin_beta_release_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:BetaRelease:list", page: 1 }
    requirements:
        page:  \d+

admin_beta_release_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:BetaRelease:filter" }

admin_beta_release_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:BetaRelease:clear" }

admin_beta_release_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:BetaRelease:show" }

admin_beta_release_new:
    path:  /new
    defaults: { _controller: "AdminBundle:BetaRelease:new" }

admin_beta_release_create:
    path:  /create
    defaults: { _controller: "AdminBundle:BetaRelease:create" }
    methods: [POST]

admin_beta_release_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:BetaRelease:edit" }

admin_beta_release_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:BetaRelease:update" }
    methods: [POST]

admin_beta_release_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:BetaRelease:delete" }
