admin_change_log_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:ChangeLog:list", page: 1 }
    requirements:
        page:  \d+

admin_change_log_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:ChangeLog:filter" }

admin_change_log_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:ChangeLog:clear" }

admin_change_log_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:ChangeLog:show" }

admin_change_log_new:
    path:  /new
    defaults: { _controller: "AdminBundle:ChangeLog:new" }

admin_change_log_create:
    path:  /create
    defaults: { _controller: "AdminBundle:ChangeLog:create" }
    methods: [POST]

admin_change_log_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:ChangeLog:edit" }

admin_change_log_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:ChangeLog:update" }
    methods: [POST]

admin_change_log_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:ChangeLog:delete" }
