admin_crash_report_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:CrashReport:list", page: 1 }
    requirements:
        page:  \d+

admin_crash_report_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:CrashReport:filter" }

admin_crash_report_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:CrashReport:clear" }

admin_crash_report_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:CrashReport:show" }

admin_crash_report_new:
    path:  /new
    defaults: { _controller: "AdminBundle:CrashReport:new" }

admin_crash_report_create:
    path:  /create
    defaults: { _controller: "AdminBundle:CrashReport:create" }
    methods: [POST]

admin_crash_report_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:CrashReport:edit" }

admin_crash_report_resolved:
    path:  /{id}/resolved
    defaults: { _controller: "AdminBundle:CrashReport:resolved" }

admin_crash_report_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:CrashReport:update" }
    methods: [POST]

admin_crash_report_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:CrashReport:delete" }

admin_crash_report_delete_all:
    path:  /delete
    defaults: { _controller: "AdminBundle:CrashReport:deleteAll" }

admin_crash_report_delete_selected:
    path:  /deleteSelected
    defaults: { _controller: "AdminBundle:CrashReport:deleteSelected" }
