admin_donator_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:Donator:list", page: 1 }
    requirements:
        page:  \d+

admin_donator_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:Donator:filter" }

admin_donator_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:Donator:clear" }

admin_donator_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:Donator:show" }

admin_donator_new:
    path:  /new
    defaults: { _controller: "AdminBundle:Donator:new" }

admin_donator_create:
    path:  /create
    defaults: { _controller: "AdminBundle:Donator:create" }
    methods: [POST]

admin_donator_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:Donator:edit" }

admin_donator_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:Donator:update" }
    methods: [POST]

admin_donator_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:Donator:delete" }
