admin_quick_start_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:QuickStart:list", page: 1 }
    requirements:
        page:  \d+

admin_quick_start_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:QuickStart:filter" }

admin_quick_start_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:QuickStart:clear" }

admin_quick_start_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:QuickStart:show" }

admin_quick_start_new:
    path:  /new
    defaults: { _controller: "AdminBundle:QuickStart:new" }

admin_quick_start_create:
    path:  /create
    defaults: { _controller: "AdminBundle:QuickStart:create" }
    methods: [POST]

admin_quick_start_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:QuickStart:edit" }

admin_quick_start_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:QuickStart:update" }
    methods: [POST]

admin_quick_start_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:QuickStart:delete" }
