admin_tip_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:Tip:list", page: 1 }
    requirements:
        page:  \d+

admin_tip_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:Tip:filter" }

admin_tip_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:Tip:clear" }

admin_tip_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:Tip:show" }

admin_tip_new:
    path:  /new
    defaults: { _controller: "AdminBundle:Tip:new" }

admin_tip_create:
    path:  /create
    defaults: { _controller: "AdminBundle:Tip:create" }
    methods: [POST]

admin_tip_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:Tip:edit" }

admin_tip_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:Tip:update" }
    methods: [POST]

admin_tip_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:Tip:delete" }
