admin_tip_holiday_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:TipHoliday:list", page: 1 }
    requirements:
        page:  \d+

admin_tip_holiday_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:TipHoliday:filter" }

admin_tip_holiday_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:TipHoliday:clear" }

admin_tip_holiday_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:TipHoliday:show" }

admin_tip_holiday_new:
    path:  /new
    defaults: { _controller: "AdminBundle:TipHoliday:new" }

admin_tip_holiday_create:
    path:  /create
    defaults: { _controller: "AdminBundle:TipHoliday:create" }
    methods: [POST]

admin_tip_holiday_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:TipHoliday:edit" }

admin_tip_holiday_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:TipHoliday:update" }
    methods: [POST]

admin_tip_holiday_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:TipHoliday:delete" }
