admin_user_list:
    path:  /{page}
    defaults: { _controller: "AdminBundle:User:list", page: 1 }
    requirements:
        page:  \d+

admin_user_filter:
    path:  /filter
    defaults: { _controller: "AdminBundle:User:filter" }

admin_user_clear:
    path:  /clear
    defaults: { _controller: "AdminBundle:User:clear" }

admin_user_show:
    path:  /{id}/show
    defaults: { _controller: "AdminBundle:User:show" }

admin_user_new:
    path:  /new
    defaults: { _controller: "AdminBundle:User:new" }

admin_user_create:
    path:  /create
    defaults: { _controller: "AdminBundle:User:create" }
    methods: [POST]

admin_user_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminBundle:User:edit" }

admin_user_update:
    path:  /{id}/update
    defaults: { _controller: "AdminBundle:User:update" }
    methods: [POST]

admin_user_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminBundle:User:delete" }
