<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120303195715 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE andro_beta_release ADD version_id INT DEFAULT NULL, DROP version");
        $this->addSql("ALTER TABLE andro_beta_release ADD CONSTRAINT FK_342728234BBC2705 FOREIGN KEY (version_id) REFERENCES andro_androirc_version (id)");
        $this->addSql("CREATE INDEX IDX_342728234BBC2705 ON andro_beta_release (version_id)");
        $this->addSql("ALTER TABLE andro_changelog ADD version_id INT DEFAULT NULL, DROP version");
        $this->addSql("ALTER TABLE andro_changelog ADD CONSTRAINT FK_C81365724BBC2705 FOREIGN KEY (version_id) REFERENCES andro_androirc_version (id)");
        $this->addSql("CREATE INDEX IDX_C81365724BBC2705 ON andro_changelog (version_id)");
        $this->addSql("ALTER TABLE andro_quick_start ADD version_min_id INT DEFAULT NULL, ADD version_max_id INT DEFAULT NULL, DROP version_min, DROP version_max");
        $this->addSql("ALTER TABLE andro_quick_start ADD CONSTRAINT FK_2C1AD845A31E1C52 FOREIGN KEY (version_min_id) REFERENCES andro_androirc_version (id)");
        $this->addSql("ALTER TABLE andro_quick_start ADD CONSTRAINT FK_2C1AD845E61C5FD0 FOREIGN KEY (version_max_id) REFERENCES andro_androirc_version (id)");
        $this->addSql("CREATE INDEX IDX_2C1AD845A31E1C52 ON andro_quick_start (version_min_id)");
        $this->addSql("CREATE INDEX IDX_2C1AD845E61C5FD0 ON andro_quick_start (version_max_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE andro_beta_release DROP FOREIGN KEY FK_342728234BBC2705");
        $this->addSql("DROP INDEX IDX_342728234BBC2705 ON andro_beta_release");
        $this->addSql("ALTER TABLE andro_beta_release ADD version VARCHAR(100) NOT NULL, DROP version_id");
        $this->addSql("ALTER TABLE andro_changelog DROP FOREIGN KEY FK_C81365724BBC2705");
        $this->addSql("DROP INDEX IDX_C81365724BBC2705 ON andro_changelog");
        $this->addSql("ALTER TABLE andro_changelog ADD version INT NOT NULL, DROP version_id");
        $this->addSql("ALTER TABLE andro_quick_start DROP FOREIGN KEY FK_2C1AD845A31E1C52");
        $this->addSql("ALTER TABLE andro_quick_start DROP FOREIGN KEY FK_2C1AD845E61C5FD0");
        $this->addSql("DROP INDEX IDX_2C1AD845A31E1C52 ON andro_quick_start");
        $this->addSql("DROP INDEX IDX_2C1AD845E61C5FD0 ON andro_quick_start");
        $this->addSql("ALTER TABLE andro_quick_start ADD version_min INT NOT NULL, ADD version_max INT NOT NULL, DROP version_min_id, DROP version_max_id");
    }
}
