<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130115193602 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE andro_logcat (id INT AUTO_INCREMENT NOT NULL, crashreport_id INT DEFAULT NULL, created DATETIME NOT NULL, logcat LONGTEXT NOT NULL, INDEX IDX_B335459B4073FA85 (crashreport_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE andro_logcat ADD CONSTRAINT FK_B335459B4073FA85 FOREIGN KEY (crashreport_id) REFERENCES andro_crash_report (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE andro_logcat");
    }
}
