<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120302195901 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE andro_android_version (id INT AUTO_INCREMENT NOT NULL, apiLevel INT NOT NULL, major INT NOT NULL, minor INT NOT NULL, revision INT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE andro_androirc_version (id INT AUTO_INCREMENT NOT NULL, state VARCHAR(30) NOT NULL, code INT NOT NULL, major INT NOT NULL, minor INT NOT NULL, revision INT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE andro_android_version");
        $this->addSql("DROP TABLE andro_androirc_version");
    }
}
